select * from (values
 ('CASA_RATIO',            'CASA Ratio',
  'Share of deposit balances held in low-cost current and savings accounts',
  '(CA + SA) / (CA + SA + TD)',
  'Open accounts, NPR balance; by branch, province, overall'),
 ('TOTAL_DEPOSITS',        'Total Deposits',
  'Total balance of all open deposit accounts (CA, SA, FD, RD)',
  'SUM(balance) where product_group in (CASA, TERM_DEPOSIT)',
  'By branch, province, overall'),
 ('LOAN_PORTFOLIO',        'Loan Portfolio',
  'Total outstanding amount owed by borrowers on open loan accounts',
  'SUM(ABS(balance)) where schm_type = LD',
  'By branch, province, overall'),
 ('LOAN_TO_DEPOSIT_RATIO', 'Loan to Deposit Ratio',
  'How much of the deposit base has been lent out',
  'Loan Portfolio / Total Deposits',
  'By branch, province, overall'),
 ('ACTIVE_ACCOUNTS',       'Active Accounts',
  'Number of open accounts',
  'COUNT(accounts) where acct_cls_flg = N',
  'By branch, province, overall'),
 ('AVG_DEPOSIT_BALANCE',   'Average Deposit Balance',
  'Average balance per open deposit account',
  'AVG(balance) where product_group in (CASA, TERM_DEPOSIT)',
  'By product category'),
 ('ACCOUNT_CLOSURE_RATE',  'Account Closure Rate',
  'Share of accounts that have been closed',
  'Closed accounts / All accounts',
  'By product category'),
 ('ACCOUNTS_PER_CUSTOMER', 'Accounts per Customer',
  'Average number of open accounts held by each customer',
  'Open accounts / Distinct customers',
  'Overall'),
 ('CARD_PENETRATION',      'Card Penetration',
  'Share of open accounts that have at least one card',
  'Open accounts with a card / Open accounts',
  'Overall'),
 ('TXN_COUNT',             'Transaction Count',
  'Number of transactions',
  'COUNT(tran_id)',
  'By month'),
 ('TXN_VALUE',             'Transaction Value',
  'Total value of transactions in NPR',
  'SUM(tran_amount_npr)',
  'By month'),
 ('NET_CASH_FLOW',         'Net Cash Flow',
  'Inflows minus outflows across all transactions in NPR',
  'SUM(credits) - SUM(debits)',
  'By month')
) as t(kpi_code, kpi_name, business_definition, formula, aggregation_grouping)